server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.2.20:3306/dev
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: ymc334859
mybatis:
  type-aliases-package: com.timezero.seckill.entity
  mappers-locations:
    - classpath:mapper/*.xml
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml